apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/ingress.yaml
- manifests/logoutput-service.yaml
- manifests/logoutputdeployment.yaml
- manifests/ping-pong-service.yaml
- manifests/pingpong-deployment.yaml
- manifests/postgres-service.yaml
- manifests/postgresdeployment.yaml
images:
- name: LOGOUTPUT/IMAGE
  newName: usermine12/dvopskube-407-logoutput
  newTag: 379a3e20813a270a16b4ea7cf532e4a7a5940eaa
- name: PINGPONG/IMAGE
  newName: usermine12/dvopskube-407-pingpong
  newTag: 379a3e20813a270a16b4ea7cf532e4a7a5940eaa
