apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: todo-project
  name: createrandomtodo
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: createrandomtodo
            image: CRONJOB/IMAGE
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DATABASE_URL
          restartPolicy: OnFailure