apiVersion: apps/v1
kind: Deployment
metadata:
  name: pseudorandstring-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pseudorandstring
  template:
    metadata:
      labels:
        app: pseudorandstring
    spec:
      containers:
        - name: pseudorandstring
          image: usermine12/dvopskube-101