apiVersion: v1
kind: Service
metadata:
  namespace: course-exercises
  name: postgres-svc
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: postgresapp