apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-project
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: usermine12/dvopskube-208-backend
          env:
          - name: PORT
            value: "3001"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: DATABASE_URL