resources:
- backend-rollout.yaml
- backend-service.yaml
- broadcaster-deployment.yaml
- frontend-rollout.yaml
- frontend-service.yaml
- ingress.yaml
- persistentvolumeclaim.yaml
- postgresdeployment.yaml
- postgres-service.yaml
- todocronjob.yaml
images:
- name: BACKEND/IMAGE
  newName: usermine12/dvopskube-408-backend
  newTag: 6f33089d6524e19a454cb9496cc026a50ff85219
- name: BROADCASTER/IMAGE
  newName: usermine12/dvopskube-408-broadcaster
  newTag: 6f33089d6524e19a454cb9496cc026a50ff85219
- name: CRONJOB/IMAGE
  newName: usermine12/dvopskube-408-job
  newTag: 6f33089d6524e19a454cb9496cc026a50ff85219
- name: FRONTEND/IMAGE
  newName: usermine12/dvopskube-408-frontend
  newTag: 6f33089d6524e19a454cb9496cc026a50ff85219
