apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/backend-deployment.yaml
  - manifests/backend-service.yaml
  - manifests/frontend-deployment.yaml
  - manifests/frontend-service.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolume.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres-deployment.yaml
  - manifests/postgres-service.yaml
  - manifests/todo-cronjob.yaml
images:
  - name: BACKEND/IMAGE
    newName: usermine12/dvopskube-303-backend
  - name: FRONTEND/IMAGE
    newName: usermine12/dvopskube-303-frontend
  - name: CRONJOB/IMAGE
    newName: usermine12/dvopskube-303-job