apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: course-exercises
  name: postgres-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard-rwo