apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: todo-volume-claim
      containers:
        - name: todo
          image: usermine12/dvopskube-113
          env:
          - name: PORT
            value: "3000"