apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: BROADCASTER/IMAGE
          env:
          - name: PORT
            value: "3000"
          - name: NATS_URL
            value: "nats://my-nats.todo-project:4222"
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
