apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-project
  name: todo-volume-claim
spec:
  storageClassName: todo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi